// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import {
    type Client,
    type ClientMeta,
    formDataBodySerializer,
    type Options as Options2,
    type RequestResult,
    type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
    CommitImportData,
    CommitImportErrors,
    CommitImportResponses,
    ExportImportErrorsData,
    ExportImportErrorsErrors,
    ExportImportErrorsResponses,
    GetImportErrorsData,
    GetImportErrorsErrors,
    GetImportErrorsResponses,
    GetImportSessionData,
    GetImportSessionErrors,
    GetImportSessionResponses,
    GetTableSchemaData,
    GetTableSchemaResponses,
    InitializeSessionData,
    InitializeSessionErrors,
    InitializeSessionResponses,
    InspectHeadersData,
    InspectHeadersErrors,
    InspectHeadersResponses,
    InspectSessionData,
    InspectSessionErrors,
    InspectSessionResponses,
    ListImportsData,
    ListImportsErrors,
    ListImportsResponses,
    SetImportMappingsData,
    SetImportMappingsErrors,
    SetImportMappingsResponses,
} from "./types.gen";
import {
    zCommitImportPath,
    zCommitImportResponse2,
    zExportImportErrorsPath,
    zExportImportErrorsResponse,
    zGetImportErrorsPath,
    zGetImportErrorsQuery,
    zGetImportErrorsResponse2,
    zGetImportSessionPath,
    zGetImportSessionResponse2,
    zGetTableSchemaPath,
    zGetTableSchemaResponse,
    zInitializeSessionBody,
    zInitializeSessionResponse2,
    zInspectHeadersBody,
    zInspectHeadersResponse2,
    zInspectSessionPath,
    zInspectSessionResponse2,
    zListImportsQuery,
    zListImportsResponse2,
    zSetImportMappingsBody,
    zSetImportMappingsPath,
    zSetImportMappingsResponse2,
} from "./zod.gen";

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never
        ? Record<string, unknown>
        : ClientMeta;
};

export const listImports = <ThrowOnError extends boolean = false>(
    options: Options<ListImportsData, ThrowOnError>,
): RequestResult<ListImportsResponses, ListImportsErrors, ThrowOnError> =>
    (options.client ?? client).get<
        ListImportsResponses,
        ListImportsErrors,
        ThrowOnError
    >({
        requestValidator: async (data) =>
            await z
                .object({
                    body: z.never().optional(),
                    path: z.never().optional(),
                    query: zListImportsQuery,
                })
                .parseAsync(data),
        responseTransformer: async (data) =>
            await zListImportsResponse2.parseAsync(data),
        url: "/api/imports",
        ...options,
    });

export const initializeSession = <ThrowOnError extends boolean = false>(
    options: Options<InitializeSessionData, ThrowOnError>,
): RequestResult<
    InitializeSessionResponses,
    InitializeSessionErrors,
    ThrowOnError
> =>
    (options.client ?? client).post<
        InitializeSessionResponses,
        InitializeSessionErrors,
        ThrowOnError
    >({
        requestValidator: async (data) =>
            await z
                .object({
                    body: zInitializeSessionBody,
                    path: z.never().optional(),
                    query: z.never().optional(),
                })
                .parseAsync(data),
        responseTransformer: async (data) =>
            await zInitializeSessionResponse2.parseAsync(data),
        url: "/api/imports/initialize",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

export const getImportSession = <ThrowOnError extends boolean = false>(
    options: Options<GetImportSessionData, ThrowOnError>,
): RequestResult<
    GetImportSessionResponses,
    GetImportSessionErrors,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetImportSessionResponses,
        GetImportSessionErrors,
        ThrowOnError
    >({
        requestValidator: async (data) =>
            await z
                .object({
                    body: z.never().optional(),
                    path: zGetImportSessionPath,
                    query: z.never().optional(),
                })
                .parseAsync(data),
        responseTransformer: async (data) =>
            await zGetImportSessionResponse2.parseAsync(data),
        url: "/api/imports/{id}",
        ...options,
    });

export const commitImport = <ThrowOnError extends boolean = false>(
    options: Options<CommitImportData, ThrowOnError>,
): RequestResult<CommitImportResponses, CommitImportErrors, ThrowOnError> =>
    (options.client ?? client).post<
        CommitImportResponses,
        CommitImportErrors,
        ThrowOnError
    >({
        requestValidator: async (data) =>
            await z
                .object({
                    body: z.never().optional(),
                    path: zCommitImportPath,
                    query: z.never().optional(),
                })
                .parseAsync(data),
        responseTransformer: async (data) =>
            await zCommitImportResponse2.parseAsync(data),
        url: "/api/imports/{id}/commit",
        ...options,
    });

export const getImportErrors = <ThrowOnError extends boolean = false>(
    options: Options<GetImportErrorsData, ThrowOnError>,
): RequestResult<
    GetImportErrorsResponses,
    GetImportErrorsErrors,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetImportErrorsResponses,
        GetImportErrorsErrors,
        ThrowOnError
    >({
        requestValidator: async (data) =>
            await z
                .object({
                    body: z.never().optional(),
                    path: zGetImportErrorsPath,
                    query: zGetImportErrorsQuery,
                })
                .parseAsync(data),
        responseTransformer: async (data) =>
            await zGetImportErrorsResponse2.parseAsync(data),
        url: "/api/imports/{id}/errors",
        ...options,
    });

export const exportImportErrors = <ThrowOnError extends boolean = false>(
    options: Options<ExportImportErrorsData, ThrowOnError>,
): RequestResult<
    ExportImportErrorsResponses,
    ExportImportErrorsErrors,
    ThrowOnError
> =>
    (options.client ?? client).get<
        ExportImportErrorsResponses,
        ExportImportErrorsErrors,
        ThrowOnError
    >({
        requestValidator: async (data) =>
            await z
                .object({
                    body: z.never().optional(),
                    path: zExportImportErrorsPath,
                    query: z.never().optional(),
                })
                .parseAsync(data),
        responseTransformer: async (data) =>
            await zExportImportErrorsResponse.parseAsync(data),
        url: "/api/imports/{id}/errors/export",
        ...options,
    });

export const inspectSession = <ThrowOnError extends boolean = false>(
    options: Options<InspectSessionData, ThrowOnError>,
): RequestResult<InspectSessionResponses, InspectSessionErrors, ThrowOnError> =>
    (options.client ?? client).get<
        InspectSessionResponses,
        InspectSessionErrors,
        ThrowOnError
    >({
        requestValidator: async (data) =>
            await z
                .object({
                    body: z.never().optional(),
                    path: zInspectSessionPath,
                    query: z.never().optional(),
                })
                .parseAsync(data),
        responseTransformer: async (data) =>
            await zInspectSessionResponse2.parseAsync(data),
        url: "/api/imports/{id}/inspect",
        ...options,
    });

export const setImportMappings = <ThrowOnError extends boolean = false>(
    options: Options<SetImportMappingsData, ThrowOnError>,
): RequestResult<
    SetImportMappingsResponses,
    SetImportMappingsErrors,
    ThrowOnError
> =>
    (options.client ?? client).post<
        SetImportMappingsResponses,
        SetImportMappingsErrors,
        ThrowOnError
    >({
        requestValidator: async (data) =>
            await z
                .object({
                    body: zSetImportMappingsBody,
                    path: zSetImportMappingsPath,
                    query: z.never().optional(),
                })
                .parseAsync(data),
        responseTransformer: async (data) =>
            await zSetImportMappingsResponse2.parseAsync(data),
        url: "/api/imports/{id}/mappings",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

export const inspectHeaders = <ThrowOnError extends boolean = false>(
    options: Options<InspectHeadersData, ThrowOnError>,
): RequestResult<InspectHeadersResponses, InspectHeadersErrors, ThrowOnError> =>
    (options.client ?? client).post<
        InspectHeadersResponses,
        InspectHeadersErrors,
        ThrowOnError
    >({
        ...formDataBodySerializer,
        requestValidator: async (data) =>
            await z
                .object({
                    body: zInspectHeadersBody,
                    path: z.never().optional(),
                    query: z.never().optional(),
                })
                .parseAsync(data),
        responseTransformer: async (data) =>
            await zInspectHeadersResponse2.parseAsync(data),
        url: "/api/ingestion/inspect-headers",
        ...options,
        headers: {
            "Content-Type": null,
            ...options.headers,
        },
    });

export const getTableSchema = <ThrowOnError extends boolean = false>(
    options: Options<GetTableSchemaData, ThrowOnError>,
): RequestResult<GetTableSchemaResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetTableSchemaResponses,
        unknown,
        ThrowOnError
    >({
        requestValidator: async (data) =>
            await z
                .object({
                    body: z.never().optional(),
                    path: zGetTableSchemaPath,
                    query: z.never().optional(),
                })
                .parseAsync(data),
        responseTransformer: async (data) =>
            await zGetTableSchemaResponse.parseAsync(data),
        url: "/api/schema/{tableName}",
        ...options,
    });
