// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: "http://localhost:3001/" | (string & {});
};

export enum ColumnDataType {
    TEXT = "Text",
    INTEGER = "Integer",
    BIG_INT = "BigInt",
    DECIMAL = "Decimal",
    BOOLEAN = "Boolean",
    DATE_TIME = "DateTime",
    DATE = "Date",
    UUID = "Uuid",
    JSON = "Json",
    BINARY = "Binary",
}

export type ColumnMapping = {
    sourceHeader: string;
    targetColumn: string;
};

export type ColumnMatch = {
    sourceHeader: string;
    targetColumn: string;
    confidence: number;
    isAutoMatched: boolean;
};

export type ColumnMetadata = {
    name: string;
    dataType: ColumnDataType;
    isNullable: boolean;
    maxLength: null | number;
    isIdentity: boolean;
    hasDefault: boolean;
    isGenerated: boolean;
    isRequired?: boolean;
    isWritable?: boolean;
    isAutoGenerated?: boolean;
};

export type ColumnSchemaDto = {
    name: string;
    dataType: string;
    isNullable: boolean;
    maxLength: null | number;
    isAutoGenerated: boolean;
};

export type CommitImportResponse = {
    id: ImportSessionId;
    status: ImportSessionStatus;
    totalProcessed: number;
    successCount: number;
    failedCount: number;
    elapsedMilliseconds: number;
    errors: IReadOnlyListOfRowError;
};

export type DictionaryOfStringAndObject = {
    [key: string]: unknown;
};

export type GetImportErrorsResponse = {
    id: ImportSessionId;
    totalErrors: number;
    page: number;
    pageSize: number;
    errors: IReadOnlyListOfRowError;
};

export type GetImportSessionResponse = {
    id: ImportSessionId;
    status: ImportSessionStatus;
    targetTable: string;
    fileName: string;
    processedRows: number;
    successRowCount: number;
    failedRowCount: number;
    errorMessage: null | string;
    mappings: IReadOnlyListOfColumnMapping;
    createdAt: string;
    completedAt: null | string;
};

export type ImportSessionId = string;

export enum ImportSessionStatus {
    INITIALIZED = "Initialized",
    MAPPED = "Mapped",
    INGESTING = "Ingesting",
    COMPLETED = "Completed",
    FAILED = "Failed",
}

export type ImportSummaryDto = {
    id: ImportSessionId;
    status: ImportSessionStatus;
    targetTable: string;
    fileName: string;
    processedRows: number;
    successRowCount: number;
    failedRowCount: number;
    createdAt: string;
    completedAt: null | string;
};

export type InitializeSessionRequest = {
    targetTable: string;
    fileName: string;
    tenantId?: null | string;
};

export type InitializeSessionResponse = {
    sessionId: ImportSessionId;
    uploadUrl: string;
    storageKey: string;
    expiresAt: string;
};

export type InspectSessionResponse = {
    sessionId: ImportSessionId;
    status: ImportSessionStatus;
    headers: IReadOnlyListOfString;
    suggestedMappings: IReadOnlyListOfColumnMatch;
    targetColumns: IReadOnlyListOfColumnMetadata;
    previewRows: IReadOnlyListOfDictionaryOfStringAndObject;
};

export type IReadOnlyListOfColumnMapping = Array<ColumnMapping>;

export type IReadOnlyListOfColumnMatch = Array<ColumnMatch>;

export type IReadOnlyListOfColumnMetadata = Array<ColumnMetadata>;

export type IReadOnlyListOfDictionaryOfStringAndObject =
    Array<DictionaryOfStringAndObject>;

export type IReadOnlyListOfImportSummaryDto = Array<ImportSummaryDto>;

export type IReadOnlyListOfRowError = Array<RowError>;

export type IReadOnlyListOfString = Array<string>;

export type ListImportsResponse = {
    page: number;
    pageSize: number;
    totalCount: number;
    items: IReadOnlyListOfImportSummaryDto;
};

export type ListOfColumnMapping = Array<ColumnMapping>;

export type ListOfColumnSchemaDto = Array<ColumnSchemaDto>;

/**
 * RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:
 * ```app.UseFastEndpoints(c =&gt; c.Errors.UseProblemDetails())```
 */
export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: number;
    instance?: string;
    traceId?: string;
    /**
     * the details of the error
     */
    detail?: null | string;
    errors?: Array<{
        /**
         * the name of the error or property of the dto that caused the error
         */
        name?: string;
        /**
         * the reason for the error
         */
        reason?: string;
        /**
         * the code of the error
         */
        code?: null | string;
        /**
         * the severity of the error
         */
        severity?: null | string;
    }>;
};

export type RowError = {
    rowNumber: number;
    column: string;
    rawValue: null | string;
    reason: string;
};

export type SetImportMappingsRequest = {
    mappings?: ListOfColumnMapping;
};

export type SetImportMappingsResponse = {
    id: ImportSessionId;
    status: ImportSessionStatus;
    mappedColumnCount: number;
};

export type ListImportsData = {
    body?: never;
    path?: never;
    query: {
        page: number;
        pageSize: number;
        status?: ImportSessionStatus;
    };
    url: "/api/imports";
};

export type ListImportsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ListImportsResponses = {
    /**
     * Success
     */
    200: ListImportsResponse;
};

export type ListImportsResponse2 =
    ListImportsResponses[keyof ListImportsResponses];

export type InitializeSessionData = {
    body: InitializeSessionRequest;
    path?: never;
    query?: never;
    url: "/api/imports/initialize";
};

export type InitializeSessionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type InitializeSessionError =
    InitializeSessionErrors[keyof InitializeSessionErrors];

export type InitializeSessionResponses = {
    /**
     * Success
     */
    200: InitializeSessionResponse;
};

export type InitializeSessionResponse2 =
    InitializeSessionResponses[keyof InitializeSessionResponses];

export type GetImportSessionData = {
    body?: never;
    path: {
        id: ImportSessionId;
    };
    query?: never;
    url: "/api/imports/{id}";
};

export type GetImportSessionErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetImportSessionResponses = {
    /**
     * Success
     */
    200: GetImportSessionResponse;
};

export type GetImportSessionResponse2 =
    GetImportSessionResponses[keyof GetImportSessionResponses];

export type CommitImportData = {
    body?: never;
    path: {
        id: ImportSessionId;
    };
    query?: never;
    url: "/api/imports/{id}/commit";
};

export type CommitImportErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type CommitImportResponses = {
    /**
     * Success
     */
    200: CommitImportResponse;
};

export type CommitImportResponse2 =
    CommitImportResponses[keyof CommitImportResponses];

export type GetImportErrorsData = {
    body?: never;
    path: {
        id: ImportSessionId;
    };
    query: {
        page: number;
        pageSize: number;
    };
    url: "/api/imports/{id}/errors";
};

export type GetImportErrorsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetImportErrorsResponses = {
    /**
     * Success
     */
    200: GetImportErrorsResponse;
};

export type GetImportErrorsResponse2 =
    GetImportErrorsResponses[keyof GetImportErrorsResponses];

export type ExportImportErrorsData = {
    body?: never;
    path: {
        id: ImportSessionId;
    };
    query?: never;
    url: "/api/imports/{id}/errors/export";
};

export type ExportImportErrorsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ExportImportErrorsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type ExportImportErrorsResponse =
    ExportImportErrorsResponses[keyof ExportImportErrorsResponses];

export type InspectSessionData = {
    body?: never;
    path: {
        id: ImportSessionId;
    };
    query?: never;
    url: "/api/imports/{id}/inspect";
};

export type InspectSessionErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type InspectSessionResponses = {
    /**
     * Success
     */
    200: InspectSessionResponse;
};

export type InspectSessionResponse2 =
    InspectSessionResponses[keyof InspectSessionResponses];

export type SetImportMappingsData = {
    body: SetImportMappingsRequest;
    path: {
        id: ImportSessionId;
    };
    query?: never;
    url: "/api/imports/{id}/mappings";
};

export type SetImportMappingsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type SetImportMappingsError =
    SetImportMappingsErrors[keyof SetImportMappingsErrors];

export type SetImportMappingsResponses = {
    /**
     * Success
     */
    200: SetImportMappingsResponse;
};

export type SetImportMappingsResponse2 =
    SetImportMappingsResponses[keyof SetImportMappingsResponses];

export type GetTableSchemaData = {
    body?: never;
    path: {
        tableName: string;
    };
    query?: never;
    url: "/api/schema/{tableName}";
};

export type GetTableSchemaResponses = {
    /**
     * Success
     */
    200: ListOfColumnSchemaDto;
};

export type GetTableSchemaResponse =
    GetTableSchemaResponses[keyof GetTableSchemaResponses];
