// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zColumnDataType = z.enum([
    "Text",
    "Integer",
    "BigInt",
    "Decimal",
    "Boolean",
    "DateTime",
    "Date",
    "Uuid",
    "Json",
    "Binary",
]);

export type ColumnDataTypeZodInput = z.input<typeof zColumnDataType>;

export type ColumnDataTypeZodOutput = z.output<typeof zColumnDataType>;

export const zColumnMapping = z.object({
    sourceHeader: z.string(),
    targetColumn: z.string(),
});

export type ColumnMappingZodInput = z.input<typeof zColumnMapping>;

export type ColumnMappingZodOutput = z.output<typeof zColumnMapping>;

export const zColumnMatch = z.object({
    sourceHeader: z.string(),
    targetColumn: z.string(),
    confidence: z.number(),
    isAutoMatched: z.boolean(),
});

export type ColumnMatchZodInput = z.input<typeof zColumnMatch>;

export type ColumnMatchZodOutput = z.output<typeof zColumnMatch>;

export const zColumnMetadata = z.object({
    name: z.string(),
    dataType: zColumnDataType,
    isNullable: z.boolean(),
    maxLength: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        })
        .nullable(),
    isIdentity: z.boolean(),
    hasDefault: z.boolean(),
    isGenerated: z.boolean(),
    isRequired: z.boolean().optional(),
    isWritable: z.boolean().optional(),
    isAutoGenerated: z.boolean().optional(),
});

export type ColumnMetadataZodInput = z.input<typeof zColumnMetadata>;

export type ColumnMetadataZodOutput = z.output<typeof zColumnMetadata>;

export const zColumnSchemaDto = z.object({
    name: z.string(),
    dataType: z.string(),
    isNullable: z.boolean(),
    maxLength: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        })
        .nullable(),
    isAutoGenerated: z.boolean(),
});

export type ColumnSchemaDtoZodInput = z.input<typeof zColumnSchemaDto>;

export type ColumnSchemaDtoZodOutput = z.output<typeof zColumnSchemaDto>;

export const zDictionaryOfStringAndObject = z.record(z.string(), z.unknown());

export type DictionaryOfStringAndObjectZodInput = z.input<
    typeof zDictionaryOfStringAndObject
>;

export type DictionaryOfStringAndObjectZodOutput = z.output<
    typeof zDictionaryOfStringAndObject
>;

export const zImportSessionId = z.uuid();

export type ImportSessionIdZodInput = z.input<typeof zImportSessionId>;

export type ImportSessionIdZodOutput = z.output<typeof zImportSessionId>;

export const zImportSessionStatus = z.enum([
    "Initialized",
    "Mapped",
    "Ingesting",
    "Completed",
    "Failed",
]);

export type ImportSessionStatusZodInput = z.input<typeof zImportSessionStatus>;

export type ImportSessionStatusZodOutput = z.output<
    typeof zImportSessionStatus
>;

export const zImportSummaryDto = z.object({
    id: zImportSessionId,
    status: zImportSessionStatus,
    targetTable: z.string(),
    fileName: z.string(),
    processedRows: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    successRowCount: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    failedRowCount: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    createdAt: z.iso.datetime({ offset: true }),
    completedAt: z.iso.datetime({ offset: true }).nullable(),
});

export type ImportSummaryDtoZodInput = z.input<typeof zImportSummaryDto>;

export type ImportSummaryDtoZodOutput = z.output<typeof zImportSummaryDto>;

export const zInitializeSessionRequest = z.object({
    targetTable: z.string().min(1),
    fileName: z.string().min(1),
    tenantId: z.string().nullish(),
});

export type InitializeSessionRequestZodInput = z.input<
    typeof zInitializeSessionRequest
>;

export type InitializeSessionRequestZodOutput = z.output<
    typeof zInitializeSessionRequest
>;

export const zInitializeSessionResponse = z.object({
    sessionId: zImportSessionId,
    uploadUrl: z.string(),
    storageKey: z.string(),
    expiresAt: z.iso.datetime({ offset: true }),
});

export type InitializeSessionResponseZodInput = z.input<
    typeof zInitializeSessionResponse
>;

export type InitializeSessionResponseZodOutput = z.output<
    typeof zInitializeSessionResponse
>;

export const zInspectHeadersRequest = z.object({
    file: z.string(),
});

export type InspectHeadersRequestZodInput = z.input<
    typeof zInspectHeadersRequest
>;

export type InspectHeadersRequestZodOutput = z.output<
    typeof zInspectHeadersRequest
>;

export const zIReadOnlyListOfColumnMapping = z.array(zColumnMapping);

export type IReadOnlyListOfColumnMappingZodInput = z.input<
    typeof zIReadOnlyListOfColumnMapping
>;

export type IReadOnlyListOfColumnMappingZodOutput = z.output<
    typeof zIReadOnlyListOfColumnMapping
>;

export const zGetImportSessionResponse = z.object({
    id: zImportSessionId,
    status: zImportSessionStatus,
    targetTable: z.string(),
    fileName: z.string(),
    processedRows: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    successRowCount: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    failedRowCount: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    errorMessage: z.string().nullable(),
    mappings: zIReadOnlyListOfColumnMapping,
    createdAt: z.iso.datetime({ offset: true }),
    completedAt: z.iso.datetime({ offset: true }).nullable(),
});

export type GetImportSessionResponseZodInput = z.input<
    typeof zGetImportSessionResponse
>;

export type GetImportSessionResponseZodOutput = z.output<
    typeof zGetImportSessionResponse
>;

export const zIReadOnlyListOfColumnMatch = z.array(zColumnMatch);

export type IReadOnlyListOfColumnMatchZodInput = z.input<
    typeof zIReadOnlyListOfColumnMatch
>;

export type IReadOnlyListOfColumnMatchZodOutput = z.output<
    typeof zIReadOnlyListOfColumnMatch
>;

export const zIReadOnlyListOfColumnMetadata = z.array(zColumnMetadata);

export type IReadOnlyListOfColumnMetadataZodInput = z.input<
    typeof zIReadOnlyListOfColumnMetadata
>;

export type IReadOnlyListOfColumnMetadataZodOutput = z.output<
    typeof zIReadOnlyListOfColumnMetadata
>;

export const zIReadOnlyListOfDictionaryOfStringAndObject = z.array(
    zDictionaryOfStringAndObject,
);

export type IReadOnlyListOfDictionaryOfStringAndObjectZodInput = z.input<
    typeof zIReadOnlyListOfDictionaryOfStringAndObject
>;

export type IReadOnlyListOfDictionaryOfStringAndObjectZodOutput = z.output<
    typeof zIReadOnlyListOfDictionaryOfStringAndObject
>;

export const zIReadOnlyListOfImportSummaryDto = z.array(zImportSummaryDto);

export type IReadOnlyListOfImportSummaryDtoZodInput = z.input<
    typeof zIReadOnlyListOfImportSummaryDto
>;

export type IReadOnlyListOfImportSummaryDtoZodOutput = z.output<
    typeof zIReadOnlyListOfImportSummaryDto
>;

export const zIReadOnlyListOfString = z.array(z.string());

export type IReadOnlyListOfStringZodInput = z.input<
    typeof zIReadOnlyListOfString
>;

export type IReadOnlyListOfStringZodOutput = z.output<
    typeof zIReadOnlyListOfString
>;

export const zInspectHeadersResponse = z.object({
    headers: zIReadOnlyListOfString,
    totalColumns: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
});

export type InspectHeadersResponseZodInput = z.input<
    typeof zInspectHeadersResponse
>;

export type InspectHeadersResponseZodOutput = z.output<
    typeof zInspectHeadersResponse
>;

export const zInspectSessionResponse = z.object({
    sessionId: zImportSessionId,
    status: zImportSessionStatus,
    headers: zIReadOnlyListOfString,
    suggestedMappings: zIReadOnlyListOfColumnMatch,
    targetColumns: zIReadOnlyListOfColumnMetadata,
    previewRows: zIReadOnlyListOfDictionaryOfStringAndObject,
});

export type InspectSessionResponseZodInput = z.input<
    typeof zInspectSessionResponse
>;

export type InspectSessionResponseZodOutput = z.output<
    typeof zInspectSessionResponse
>;

export const zListImportsResponse = z.object({
    page: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    pageSize: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    totalCount: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    items: zIReadOnlyListOfImportSummaryDto,
});

export type ListImportsResponseZodInput = z.input<typeof zListImportsResponse>;

export type ListImportsResponseZodOutput = z.output<
    typeof zListImportsResponse
>;

export const zListOfColumnMapping = z.array(zColumnMapping);

export type ListOfColumnMappingZodInput = z.input<typeof zListOfColumnMapping>;

export type ListOfColumnMappingZodOutput = z.output<
    typeof zListOfColumnMapping
>;

export const zListOfColumnSchemaDto = z.array(zColumnSchemaDto);

export type ListOfColumnSchemaDtoZodInput = z.input<
    typeof zListOfColumnSchemaDto
>;

export type ListOfColumnSchemaDtoZodOutput = z.output<
    typeof zListOfColumnSchemaDto
>;

/**
 * RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:
 * ```app.UseFastEndpoints(c =&gt; c.Errors.UseProblemDetails())```
 */
export const zProblemDetails = z.object({
    type: z
        .string()
        .nullish()
        .default("https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1"),
    title: z
        .string()
        .nullish()
        .default("One or more validation errors occurred."),
    status: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        })
        .optional()
        .default(400),
    instance: z.string().optional().default("/api/route"),
    traceId: z.string().optional().default("0HMPNHL0JHL76:00000001"),
    detail: z.string().nullish(),
    errors: z
        .array(
            z.object({
                name: z.string().optional().default("Error or field name"),
                reason: z.string().optional().default("Error reason"),
                code: z.string().nullish(),
                severity: z.string().nullish(),
            }),
        )
        .optional(),
});

export type ProblemDetailsZodInput = z.input<typeof zProblemDetails>;

export type ProblemDetailsZodOutput = z.output<typeof zProblemDetails>;

export const zRowError = z.object({
    rowNumber: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    column: z.string(),
    rawValue: z.string().nullable(),
    reason: z.string(),
});

export type RowErrorZodInput = z.input<typeof zRowError>;

export type RowErrorZodOutput = z.output<typeof zRowError>;

export const zIReadOnlyListOfRowError = z.array(zRowError);

export type IReadOnlyListOfRowErrorZodInput = z.input<
    typeof zIReadOnlyListOfRowError
>;

export type IReadOnlyListOfRowErrorZodOutput = z.output<
    typeof zIReadOnlyListOfRowError
>;

export const zCommitImportResponse = z.object({
    id: zImportSessionId,
    status: zImportSessionStatus,
    totalProcessed: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    successCount: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    failedCount: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    elapsedMilliseconds: z.coerce
        .bigint()
        .min(BigInt("-9223372036854775808"), {
            error: "Invalid value: Expected int64 to be >= -9223372036854775808",
        })
        .max(BigInt("9223372036854775807"), {
            error: "Invalid value: Expected int64 to be <= 9223372036854775807",
        }),
    errors: zIReadOnlyListOfRowError,
});

export type CommitImportResponseZodInput = z.input<
    typeof zCommitImportResponse
>;

export type CommitImportResponseZodOutput = z.output<
    typeof zCommitImportResponse
>;

export const zGetImportErrorsResponse = z.object({
    id: zImportSessionId,
    totalErrors: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    page: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    pageSize: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    errors: zIReadOnlyListOfRowError,
});

export type GetImportErrorsResponseZodInput = z.input<
    typeof zGetImportErrorsResponse
>;

export type GetImportErrorsResponseZodOutput = z.output<
    typeof zGetImportErrorsResponse
>;

export const zSetImportMappingsRequest = z.object({
    mappings: zListOfColumnMapping.optional(),
});

export type SetImportMappingsRequestZodInput = z.input<
    typeof zSetImportMappingsRequest
>;

export type SetImportMappingsRequestZodOutput = z.output<
    typeof zSetImportMappingsRequest
>;

export const zSetImportMappingsResponse = z.object({
    id: zImportSessionId,
    status: zImportSessionStatus,
    mappedColumnCount: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
});

export type SetImportMappingsResponseZodInput = z.input<
    typeof zSetImportMappingsResponse
>;

export type SetImportMappingsResponseZodOutput = z.output<
    typeof zSetImportMappingsResponse
>;

export const zListImportsQuery = z.object({
    page: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    pageSize: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    status: zImportSessionStatus.optional(),
});

export type ListImportsQueryZodInput = z.input<typeof zListImportsQuery>;

export type ListImportsQueryZodOutput = z.output<typeof zListImportsQuery>;

/**
 * Success
 */
export const zListImportsResponse2 = zListImportsResponse;

export type ListImportsResponseZodInput2 = z.input<
    typeof zListImportsResponse2
>;

export type ListImportsResponseZodOutput2 = z.output<
    typeof zListImportsResponse2
>;

export const zInitializeSessionBody = zInitializeSessionRequest;

export type InitializeSessionBodyZodInput = z.input<
    typeof zInitializeSessionBody
>;

export type InitializeSessionBodyZodOutput = z.output<
    typeof zInitializeSessionBody
>;

/**
 * Success
 */
export const zInitializeSessionResponse2 = zInitializeSessionResponse;

export type InitializeSessionResponseZodInput2 = z.input<
    typeof zInitializeSessionResponse2
>;

export type InitializeSessionResponseZodOutput2 = z.output<
    typeof zInitializeSessionResponse2
>;

export const zGetImportSessionPath = z.object({
    id: zImportSessionId,
});

export type GetImportSessionPathZodInput = z.input<
    typeof zGetImportSessionPath
>;

export type GetImportSessionPathZodOutput = z.output<
    typeof zGetImportSessionPath
>;

/**
 * Success
 */
export const zGetImportSessionResponse2 = zGetImportSessionResponse;

export type GetImportSessionResponseZodInput2 = z.input<
    typeof zGetImportSessionResponse2
>;

export type GetImportSessionResponseZodOutput2 = z.output<
    typeof zGetImportSessionResponse2
>;

export const zCommitImportPath = z.object({
    id: zImportSessionId,
});

export type CommitImportPathZodInput = z.input<typeof zCommitImportPath>;

export type CommitImportPathZodOutput = z.output<typeof zCommitImportPath>;

/**
 * Success
 */
export const zCommitImportResponse2 = zCommitImportResponse;

export type CommitImportResponseZodInput2 = z.input<
    typeof zCommitImportResponse2
>;

export type CommitImportResponseZodOutput2 = z.output<
    typeof zCommitImportResponse2
>;

export const zGetImportErrorsPath = z.object({
    id: zImportSessionId,
});

export type GetImportErrorsPathZodInput = z.input<typeof zGetImportErrorsPath>;

export type GetImportErrorsPathZodOutput = z.output<
    typeof zGetImportErrorsPath
>;

export const zGetImportErrorsQuery = z.object({
    page: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
    pageSize: z
        .int()
        .min(-2147483648, {
            error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
            error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
});

export type GetImportErrorsQueryZodInput = z.input<
    typeof zGetImportErrorsQuery
>;

export type GetImportErrorsQueryZodOutput = z.output<
    typeof zGetImportErrorsQuery
>;

/**
 * Success
 */
export const zGetImportErrorsResponse2 = zGetImportErrorsResponse;

export type GetImportErrorsResponseZodInput2 = z.input<
    typeof zGetImportErrorsResponse2
>;

export type GetImportErrorsResponseZodOutput2 = z.output<
    typeof zGetImportErrorsResponse2
>;

export const zExportImportErrorsPath = z.object({
    id: zImportSessionId,
});

export type ExportImportErrorsPathZodInput = z.input<
    typeof zExportImportErrorsPath
>;

export type ExportImportErrorsPathZodOutput = z.output<
    typeof zExportImportErrorsPath
>;

/**
 * No Content
 */
export const zExportImportErrorsResponse = z.void();

export type ExportImportErrorsResponseZodInput = z.input<
    typeof zExportImportErrorsResponse
>;

export type ExportImportErrorsResponseZodOutput = z.output<
    typeof zExportImportErrorsResponse
>;

export const zInspectSessionPath = z.object({
    id: zImportSessionId,
});

export type InspectSessionPathZodInput = z.input<typeof zInspectSessionPath>;

export type InspectSessionPathZodOutput = z.output<typeof zInspectSessionPath>;

/**
 * Success
 */
export const zInspectSessionResponse2 = zInspectSessionResponse;

export type InspectSessionResponseZodInput2 = z.input<
    typeof zInspectSessionResponse2
>;

export type InspectSessionResponseZodOutput2 = z.output<
    typeof zInspectSessionResponse2
>;

export const zSetImportMappingsBody = zSetImportMappingsRequest;

export type SetImportMappingsBodyZodInput = z.input<
    typeof zSetImportMappingsBody
>;

export type SetImportMappingsBodyZodOutput = z.output<
    typeof zSetImportMappingsBody
>;

export const zSetImportMappingsPath = z.object({
    id: zImportSessionId,
});

export type SetImportMappingsPathZodInput = z.input<
    typeof zSetImportMappingsPath
>;

export type SetImportMappingsPathZodOutput = z.output<
    typeof zSetImportMappingsPath
>;

/**
 * Success
 */
export const zSetImportMappingsResponse2 = zSetImportMappingsResponse;

export type SetImportMappingsResponseZodInput2 = z.input<
    typeof zSetImportMappingsResponse2
>;

export type SetImportMappingsResponseZodOutput2 = z.output<
    typeof zSetImportMappingsResponse2
>;

export const zInspectHeadersBody = zInspectHeadersRequest;

export type InspectHeadersBodyZodInput = z.input<typeof zInspectHeadersBody>;

export type InspectHeadersBodyZodOutput = z.output<typeof zInspectHeadersBody>;

/**
 * Success
 */
export const zInspectHeadersResponse2 = zInspectHeadersResponse;

export type InspectHeadersResponseZodInput2 = z.input<
    typeof zInspectHeadersResponse2
>;

export type InspectHeadersResponseZodOutput2 = z.output<
    typeof zInspectHeadersResponse2
>;

export const zGetTableSchemaPath = z.object({
    tableName: z.string(),
});

export type GetTableSchemaPathZodInput = z.input<typeof zGetTableSchemaPath>;

export type GetTableSchemaPathZodOutput = z.output<typeof zGetTableSchemaPath>;

/**
 * Success
 */
export const zGetTableSchemaResponse = zListOfColumnSchemaDto;

export type GetTableSchemaResponseZodInput = z.input<
    typeof zGetTableSchemaResponse
>;

export type GetTableSchemaResponseZodOutput = z.output<
    typeof zGetTableSchemaResponse
>;
