// This file is auto-generated by @hey-api/openapi-ts

import {
    type DefaultError,
    type InfiniteData,
    infiniteQueryOptions,
    queryOptions,
    type UseMutationOptions,
} from "@tanstack/vue-query";

import { client } from "../client.gen";
import {
    commitImport,
    exportImportErrors,
    getImportErrors,
    getImportSession,
    getTableSchema,
    initializeSession,
    inspectHeaders,
    inspectSession,
    listImports,
    type Options,
    setImportMappings,
} from "../sdk.gen";
import type {
    CommitImportData,
    CommitImportResponse2,
    ExportImportErrorsData,
    ExportImportErrorsResponse,
    GetImportErrorsData,
    GetImportErrorsResponse2,
    GetImportSessionData,
    GetImportSessionResponse2,
    GetTableSchemaData,
    GetTableSchemaResponse,
    InitializeSessionData,
    InitializeSessionError,
    InitializeSessionResponse2,
    InspectHeadersData,
    InspectHeadersError,
    InspectHeadersResponse2,
    InspectSessionData,
    InspectSessionResponse2,
    ListImportsData,
    ListImportsResponse2,
    SetImportMappingsData,
    SetImportMappingsError,
    SetImportMappingsResponse2,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    },
];

const createQueryKey = <TOptions extends Options>(
    id: string,
    options?: TOptions,
    infinite?: boolean,
    tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
    const params: QueryKey<TOptions>[0] = {
        _id: id,
        baseUrl:
            options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
    } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listImportsQueryKey = (options: Options<ListImportsData>) =>
    createQueryKey("listImports", options);

export const listImportsOptions = (options: Options<ListImportsData>) =>
    queryOptions<
        ListImportsResponse2,
        DefaultError,
        ListImportsResponse2,
        ReturnType<typeof listImportsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await listImports({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: listImportsQueryKey(options),
    });

const createInfiniteParams = <
    K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
    queryKey: QueryKey<Options>,
    page: K,
) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...(queryKey[0].body as any),
            ...(page.body as any),
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers,
        };
    }
    if (page.path) {
        params.path = {
            ...(queryKey[0].path as any),
            ...(page.path as any),
        };
    }
    if (page.query) {
        params.query = {
            ...(queryKey[0].query as any),
            ...(page.query as any),
        };
    }
    return params as unknown as typeof page;
};

export const listImportsInfiniteQueryKey = (
    options: Options<ListImportsData>,
): QueryKey<Options<ListImportsData>> =>
    createQueryKey("listImports", options, true);

export const listImportsInfiniteOptions = (
    options: Options<ListImportsData>,
) => {
    const opts = infiniteQueryOptions<
        ListImportsResponse2,
        DefaultError,
        InfiniteData<ListImportsResponse2>,
        QueryKey<Options<ListImportsData>>,
        | number
        | Pick<
              QueryKey<Options<ListImportsData>>[0],
              "body" | "headers" | "path" | "query"
          >
    >(
        // @ts-ignore
        {
            queryFn: async ({ pageParam, queryKey, signal }) => {
                // @ts-ignore
                const page: Pick<
                    QueryKey<Options<ListImportsData>>[0],
                    "body" | "headers" | "path" | "query"
                > =
                    typeof pageParam === "object"
                        ? pageParam
                        : {
                              query: {
                                  page: pageParam,
                              },
                          };
                const params = createInfiniteParams(queryKey, page);
                const { data } = await listImports({
                    ...options,
                    ...params,
                    signal,
                    throwOnError: true,
                });
                return data;
            },
            queryKey: listImportsInfiniteQueryKey(options),
        },
    );
    return opts as Omit<typeof opts, "initialData">;
};

export const initializeSessionMutation = (
    options?: Partial<Options<InitializeSessionData>>,
): UseMutationOptions<
    InitializeSessionResponse2,
    InitializeSessionError,
    Options<InitializeSessionData>
> => {
    const mutationOptions: UseMutationOptions<
        InitializeSessionResponse2,
        InitializeSessionError,
        Options<InitializeSessionData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await initializeSession({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};

export const getImportSessionQueryKey = (
    options: Options<GetImportSessionData>,
) => createQueryKey("getImportSession", options);

export const getImportSessionOptions = (
    options: Options<GetImportSessionData>,
) =>
    queryOptions<
        GetImportSessionResponse2,
        DefaultError,
        GetImportSessionResponse2,
        ReturnType<typeof getImportSessionQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getImportSession({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: getImportSessionQueryKey(options),
    });

export const commitImportMutation = (
    options?: Partial<Options<CommitImportData>>,
): UseMutationOptions<
    CommitImportResponse2,
    DefaultError,
    Options<CommitImportData>
> => {
    const mutationOptions: UseMutationOptions<
        CommitImportResponse2,
        DefaultError,
        Options<CommitImportData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await commitImport({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};

export const getImportErrorsQueryKey = (
    options: Options<GetImportErrorsData>,
) => createQueryKey("getImportErrors", options);

export const getImportErrorsOptions = (options: Options<GetImportErrorsData>) =>
    queryOptions<
        GetImportErrorsResponse2,
        DefaultError,
        GetImportErrorsResponse2,
        ReturnType<typeof getImportErrorsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getImportErrors({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: getImportErrorsQueryKey(options),
    });

export const getImportErrorsInfiniteQueryKey = (
    options: Options<GetImportErrorsData>,
): QueryKey<Options<GetImportErrorsData>> =>
    createQueryKey("getImportErrors", options, true);

export const getImportErrorsInfiniteOptions = (
    options: Options<GetImportErrorsData>,
) => {
    const opts = infiniteQueryOptions<
        GetImportErrorsResponse2,
        DefaultError,
        InfiniteData<GetImportErrorsResponse2>,
        QueryKey<Options<GetImportErrorsData>>,
        | number
        | Pick<
              QueryKey<Options<GetImportErrorsData>>[0],
              "body" | "headers" | "path" | "query"
          >
    >(
        // @ts-ignore
        {
            queryFn: async ({ pageParam, queryKey, signal }) => {
                // @ts-ignore
                const page: Pick<
                    QueryKey<Options<GetImportErrorsData>>[0],
                    "body" | "headers" | "path" | "query"
                > =
                    typeof pageParam === "object"
                        ? pageParam
                        : {
                              query: {
                                  page: pageParam,
                              },
                          };
                const params = createInfiniteParams(queryKey, page);
                const { data } = await getImportErrors({
                    ...options,
                    ...params,
                    signal,
                    throwOnError: true,
                });
                return data;
            },
            queryKey: getImportErrorsInfiniteQueryKey(options),
        },
    );
    return opts as Omit<typeof opts, "initialData">;
};

export const exportImportErrorsQueryKey = (
    options: Options<ExportImportErrorsData>,
) => createQueryKey("exportImportErrors", options);

export const exportImportErrorsOptions = (
    options: Options<ExportImportErrorsData>,
) =>
    queryOptions<
        ExportImportErrorsResponse,
        DefaultError,
        ExportImportErrorsResponse,
        ReturnType<typeof exportImportErrorsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exportImportErrors({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: exportImportErrorsQueryKey(options),
    });

export const inspectSessionQueryKey = (options: Options<InspectSessionData>) =>
    createQueryKey("inspectSession", options);

export const inspectSessionOptions = (options: Options<InspectSessionData>) =>
    queryOptions<
        InspectSessionResponse2,
        DefaultError,
        InspectSessionResponse2,
        ReturnType<typeof inspectSessionQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await inspectSession({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: inspectSessionQueryKey(options),
    });

export const setImportMappingsMutation = (
    options?: Partial<Options<SetImportMappingsData>>,
): UseMutationOptions<
    SetImportMappingsResponse2,
    SetImportMappingsError,
    Options<SetImportMappingsData>
> => {
    const mutationOptions: UseMutationOptions<
        SetImportMappingsResponse2,
        SetImportMappingsError,
        Options<SetImportMappingsData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await setImportMappings({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};

export const inspectHeadersMutation = (
    options?: Partial<Options<InspectHeadersData>>,
): UseMutationOptions<
    InspectHeadersResponse2,
    InspectHeadersError,
    Options<InspectHeadersData>
> => {
    const mutationOptions: UseMutationOptions<
        InspectHeadersResponse2,
        InspectHeadersError,
        Options<InspectHeadersData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await inspectHeaders({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};

export const getTableSchemaQueryKey = (options: Options<GetTableSchemaData>) =>
    createQueryKey("getTableSchema", options);

export const getTableSchemaOptions = (options: Options<GetTableSchemaData>) =>
    queryOptions<
        GetTableSchemaResponse,
        DefaultError,
        GetTableSchemaResponse,
        ReturnType<typeof getTableSchemaQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getTableSchema({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: getTableSchemaQueryKey(options),
    });
