using System.ComponentModel.DataAnnotations;
using Bulkivore.Api.Domain.Schema;
using FastEndpoints;

namespace Bulkivore.Api.Endpoints.Schema;

public class GetTableSchemaEndpoint(ISchemaInspector schemaInspector)
    : Ep.Req<GetTableSchemaRequest>.Res<List<ColumnSchemaDto>>
{
    public override void Configure()
    {
        Get("schema/{TableName}");
        AllowAnonymous();
    }

    public override async Task HandleAsync(GetTableSchemaRequest req, CancellationToken ct)
    {
        var schema = await schemaInspector.InspectTableAsync(req.TableName, ct: ct);

        if (schema.Count == 0)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        var response = schema.Values.Select(c => new ColumnSchemaDto(
            Name: c.Name,
            DataType: c.DataType.ToString(),
            IsNullable: c.IsNullable,
            MaxLength: c.MaxLength,
            IsAutoGenerated: c.IsAutoGenerated
        )).ToList();

        await Send.OkAsync(response, ct);
    }
}

public class GetTableSchemaRequest
{
    [RouteParam, Required]
    public string TableName { get; set; } = string.Empty;
}

public sealed record ColumnSchemaDto(
    string Name,
    string DataType,
    bool IsNullable,
    int? MaxLength,
    bool IsAutoGenerated
);
