// <auto-generated />
using System;
using System.Collections.Generic;
using Bulkivore.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bulkivore.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906170200_UpdateImportSessionSchema")]
    partial class UpdateImportSessionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bulkivore.Api.Domain.Ingestion.ImportSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<IReadOnlyDictionary<string, string>>("ColumnMappings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("column_mappings");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("FailedRowCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_row_count");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<int>("SuccessRowCount")
                        .HasColumnType("integer")
                        .HasColumnName("success_row_count");

                    b.Property<string>("TargetTable")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_table");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_import_sessions");

                    b.HasIndex("TenantId", "TargetTable")
                        .HasDatabaseName("ix_import_sessions_tenant_target_table");

                    b.ToTable("import_sessions", (string)null);
                });

            modelBuilder.Entity("Bulkivore.Api.Domain.Ingestion.ImportSession", b =>
                {
                    b.OwnsMany("Bulkivore.Api.Domain.Ingestion.RowError", "RowErrors", b1 =>
                        {
                            b1.Property<Guid>("ImportSessionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.HasKey("ImportSessionId", "__synthesizedOrdinal");

                            b1.ToTable("import_sessions");

                            b1
                                .ToJson("row_errors")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ImportSessionId")
                                .HasConstraintName("fk_import_sessions_import_sessions_import_session_id");
                        });

                    b.Navigation("RowErrors");
                });
#pragma warning restore 612, 618
        }
    }
}
