<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FastEndpoints.Testing" Version="8.4.0-beta.3"/>
        <PackageReference Include="TUnit.Aspire" Version="1.6*"/>
        <PackageReference Include="TUnit.Assertions.Should" Version="1.66.16-beta"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Net"/>
        <Using Include="Microsoft.Extensions.DependencyInjection"/>
        <Using Include="Aspire.Hosting.ApplicationModel"/>
        <Using Include="Aspire.Hosting.Testing"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Bulkivore.Api\Bulkivore.Api.csproj"/>
        <ProjectReference Include="..\..\src\Bulkivore.AppHost\Bulkivore.AppHost.csproj"/>
    </ItemGroup>

</Project>
