<Project Sdk="Aspire.AppHost.Sdk/13.5.2">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AspireUseCliBundle>true</AspireUseCliBundle>
        <UserSecretsId>d1b05ca7-3acd-4e40-a425-cef2888f5e57</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Bulkivore.Api\Bulkivore.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.Docker" Version="13.5.3" />
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
      <PackageReference Include="CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions" Version="13.5.0" />
    </ItemGroup>

</Project>
