using Vogen;

namespace Bulkivore.Api.Domain.Schema;

[ValueObject<(string, ColumnDataType, bool, int?, bool, bool, bool)>]
public readonly partial record struct ColumnMetadata
{
    public static readonly ColumnMetadata Empty = From(
        (
            string.Empty,
            ColumnDataType.Text,
            true, // IsNullable
            null, // MaxLength
            false, // IsIdentity
            false, // HasDefault
            false // IsGenerated
        )
    );

    // Catalog properties
    public string Name => Value.Item1;
    public ColumnDataType DataType => Value.Item2;
    public bool IsNullable => Value.Item3;
    public int? MaxLength => Value.Item4;
    public bool IsIdentity => Value.Item5;
    public bool HasDefault => Value.Item6;
    public bool IsGenerated => Value.Item7;

    // Computed domain rules (Engine-agnostic)
    public bool IsRequired => !IsNullable && !IsIdentity && !HasDefault && !IsGenerated;
    public bool IsWritable => !IsGenerated;

    // Kept as a computed alias for backwards compatibility with existing callers/UI
    public bool IsAutoGenerated => IsIdentity || HasDefault || IsGenerated;

    public static ErrorOr<ColumnMetadata> Create(
        string name,
        ColumnDataType dataType,
        bool isNullable,
        int? length = null,
        bool isIdentity = false,
        bool hasDefault = false,
        bool isGenerated = false)
    {
        var result = TryFrom((name, dataType, isNullable, length, isIdentity, hasDefault, isGenerated));
        if (result.IsSuccess)
        {
            return result.ValueObject;
        }

        return Error.Validation(description: result.Error.ErrorMessage);
    }

    private static Validation Validate((string, ColumnDataType, bool, int?, bool, bool, bool) input)
    {
        return !string.IsNullOrWhiteSpace(input.Item1)
            ? Validation.Ok
            : Validation.Invalid("Column name cannot be empty");
    }

    private static (string, ColumnDataType, bool, int?, bool, bool, bool) NormalizeInput(
        (string, ColumnDataType, bool, int?, bool, bool, bool) input)
    {
        input.Item1 = input.Item1.Trim();
        input.Item4 = input.Item4 > 0 ? input.Item4 : null;
        return input;
    }
}
