using Vogen;

namespace Bulkivore.Api.Domain.Schema;

public sealed record ColumnMetadata(
    string Name,
    ColumnDataType DataType,
    bool IsNullable,
    int? MaxLength,
    bool IsIdentity,
    bool HasDefault,
    bool IsGenerated
)
{
    public static readonly ColumnMetadata Empty = new(
        string.Empty,
        ColumnDataType.Text,
        true,
        null,
        false,
        false,
        false);

    // Computed domain rules (Engine-agnostic)
    public bool IsRequired => !IsNullable && !IsIdentity && !HasDefault && !IsGenerated;
    public bool IsWritable => !IsGenerated;

    // Kept as a computed alias for backwards compatibility with existing callers/UI
    public bool IsAutoGenerated => IsIdentity || HasDefault || IsGenerated;

    public static ErrorOr<ColumnMetadata> Create(
        string name,
        ColumnDataType dataType,
        bool isNullable,
        int? maxLength = null,
        bool isIdentity = false,
        bool hasDefault = false,
        bool isGenerated = false)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return Error.Validation(description: "Column name cannot be empty");
        }

        return new ColumnMetadata(
            name.Trim(),
            dataType,
            isNullable,
            maxLength,
            isIdentity,
            hasDefault,
            isGenerated);
    }
}
