using Vogen;

namespace Bulkivore.Api.Domain.Schema;

public sealed record ColumnMetadata
{
    public static readonly ColumnMetadata Empty = new(
        string.Empty,
        ColumnDataType.Text,
        isNullable: true,
        maxLength: null,
        isIdentity: false,
        hasDefault: false,
        isGenerated: false
    );

    // Catalog properties
    public string Name { get; }
    public ColumnDataType DataType { get; }
    public bool IsNullable { get; }
    public int? MaxLength { get; }
    public bool IsIdentity { get; }
    public bool HasDefault { get; }
    public bool IsGenerated { get; }

    // Computed domain rules (Engine-agnostic)
    public bool IsRequired => !IsNullable && !IsIdentity && !HasDefault && !IsGenerated;
    public bool IsWritable => !IsGenerated;

    // Kept as a computed alias for backwards compatibility with existing callers/UI
    public bool IsAutoGenerated => IsIdentity || HasDefault || IsGenerated;

    private ColumnMetadata(
        string name,
        ColumnDataType dataType,
        bool isNullable,
        int? maxLength = null,
        bool isIdentity = false,
        bool hasDefault = false,
        bool isGenerated = false)
    {
        Name = name;
        DataType = dataType;
        IsNullable = isNullable;
        MaxLength = maxLength > 0 ? maxLength : null;
        IsIdentity = isIdentity;
        HasDefault = hasDefault;
        IsGenerated = isGenerated;
    }

    public static ErrorOr<ColumnMetadata> Create(
        string name,
        ColumnDataType dataType,
        bool isNullable,
        int? maxLength = null,
        bool isIdentity = false,
        bool hasDefault = false,
        bool isGenerated = false)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return Error.Validation(description: "Column name cannot be empty");
        }

        return new ColumnMetadata(
            name.Trim(),
            dataType,
            isNullable,
            maxLength,
            isIdentity,
            hasDefault,
            isGenerated
        );
    }
}
